bulletin_board_system/bulletin/urls.py
from django.conf.urls import url

from . import views

app_name = 'bulletin'
urlpatterns = [
    url(r'^$', views.BoardListView.as_view(), name='board-list'),
    url(r'^board/(?P<pk>\d+)/$', views.ThreadListView.as_view(), name='thread-list'),
    url(r'^thread/(?P<pk>\d+)/$', views.PostListView.as_view(), name='post-list'),
    url(r'^thread/(?P<pk>\d+)/sticky$', views.StickyThreadView.as_view(), name='thread-sticky'),
    url(r'^thread/(?P<pk>\d+)/unsticky$', views.UnstickyThreadView.as_view(), name='thread-unsticky'),
    url(r'^thread/(?P<pk>\d+)/lock', views.LockThreadView.as_view(), name='thread-lock'),
    url(r'^thread/(?P<pk>\d+)/unlock', views.UnlockThreadView.as_view(), name='thread-unlock'),
]

bulletin_board_system/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^(?P<username>[\w.@+-]+)/ban/$',
        view=views.BanUserView.as_view(),
        name='ban'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/unban/$',
        view=views.UnbanUserView.as_view(),
        name='unban'
    ),
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/bulletin/', permanent=False), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('bulletin_board_system.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^bulletin/', include('bulletin_board_system.bulletin.urls'))


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

bulletin_board_system/bulletin/models.py
from django.db import models
from django.db.models import Count, Sum
from django.contrib.auth import get_user_model
from markdownx.models import MarkdownxField
from django.core.exceptions import ValidationError


# Create your models here.
class Board(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ('-created_at', 'name')

    def __str__(self):
        return self.name

    def get_thread_count(self):
        return self.thread_set.count()

    def get_post_count(self):
        threads = self.thread_set.annotate(num_posts=Count('post'))
        if threads:
            return threads.aggregate(Sum('num_posts')).get('num_posts__sum')
        else:
            return 0


class Thread(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    sticky = models.BooleanField(default=False)
    locked = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ('-created_at', 'title')

    def __str__(self):
        return self.title

    def get_post_count(self):
        return self.post_set.count()

    def get_last_reply(self):
        posts = self.post_set.all().order_by('-created_at')
        if posts.count() > 0:
            return posts[0]
        else:
            return None


class Post(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    message = MarkdownxField()
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)

    class Meta:
        ordering = ('created_at', )

    def __str__(self):
        return '{0.thread} - {0.created_at}'.format(self)

    def get_user_post_count(self):
        return self.user.post_set.count()

bulletin_board_system/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from model_utils.choices import Choices


@python_2_unicode_compatible
class User(AbstractUser):
    GENDER_CHOICES = Choices(
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other'),
        ('not_specified', 'Not Specified')
    )
    REQUIRED_FIELDS = AbstractUser.REQUIRED_FIELDS + ['about_myself',
                                                      'date_of_birth',
                                                      'hometown',
                                                      'present_location']

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    about_myself = models.TextField(max_length=1000)
    date_of_birth = models.DateField()
    hometown = models.CharField(max_length=200)
    present_location = models.CharField(max_length=200)
    skype = models.CharField(max_length=200, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, default=GENDER_CHOICES.not_specified, max_length=20)
    interests = models.TextField(max_length=300, null=True, blank=True)
    banned = models.BooleanField(default=False)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

bulletin_board_system/bulletin/forms.py
from django.forms import ModelForm
from markdownx.fields import MarkdownxFormField
from django.core.exceptions import ValidationError

from .models import Thread, Post, Board


class BoardForm(ModelForm):

    def clean(self):
        if self.current_user.banned:
            raise ValidationError('You are banned! You cannot create boards.')
        return self.cleaned_data


class ThreadForm(ModelForm):
    class Meta:
        model = Thread
        fields = ('title', )


class PostForm(ModelForm):
    message = MarkdownxFormField()

    class Meta:
        model = Post
        fields = ('message', )

bulletin_board_system/bulletin/views.py
from django.views.generic import ListView, View
from django.views.generic.edit import FormMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.db.models import Max
from braces.views import LoginRequiredMixin, UserPassesTestMixin

from .models import Board, Thread, Post
from .forms import ThreadForm, PostForm
from .permissions import user_is_active_moderator_or_admin


LOGIN_URL = '/accounts/login/'


# Create your views here.
class BoardListView(ListView):
    model = Board


class ThreadListView(LoginRequiredMixin, FormMixin, ListView):
    model = Thread
    form_class = ThreadForm
    paginate_by = 2
    login_url = LOGIN_URL
    redirect_unauthenticated_users = True

    def get_queryset(self):
        """
        Return only the non-sticky threads for pagination. Sticky threads
        must always be on top.
        """
        board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        threads = board.thread_set.filter(sticky=False)
        threads = threads.annotate(last_post_time=Max('post__created_at'))
        return threads.order_by('-last_post_time')

    def get_context_data(self, **kwargs):
        context = super(ThreadListView, self).get_context_data(**kwargs)
        board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        context['board'] = board
        context['sticky_threads'] = board.thread_set.filter(sticky=True)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden('You must be logged in to perform this action.')
        form = self.get_form()
        if request.user.banned:
            return HttpResponseForbidden('You are banned! You cannot create threads or posts.')
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse('bulletin:thread-list', kwargs={'pk': self.kwargs.get('pk')})

    def form_valid(self, form):
        new_thread = form.save(commit=False)
        new_thread.user = self.request.user
        board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        new_thread.board = board
        new_thread.save()
        return super(ThreadListView, self).form_valid(form)


class PostListView(LoginRequiredMixin, FormMixin, ListView):
    model = Post
    form_class = PostForm
    paginate_by = 2
    login_url = LOGIN_URL
    redirect_unauthenticated_users = True

    def get_queryset(self):
        """
        Filter by the thread
        """
        thread = get_object_or_404(Thread, pk=self.kwargs.get('pk'))
        return thread.post_set.all()

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        thread = get_object_or_404(Thread, pk=self.kwargs.get('pk'))
        context['thread'] = thread
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if request.user.banned:
            return HttpResponseForbidden('You are banned! You cannot create threads or posts.')
        thread_pk = self.kwargs.get('pk')
        thread = get_object_or_404(Thread, pk=thread_pk)
        if not thread.locked:
            if form.is_valid():
                return self.form_valid(form)
            else:
                return self.form_invalid(form)
        else:
            return HttpResponseForbidden('You cannot create posts on a locked thread.')

    def get_success_url(self):
        return reverse('bulletin:post-list', kwargs={'pk': self.kwargs.get('pk')})

    def form_valid(self, form):
        new_post = form.save(commit=False)
        new_post.user = self.request.user
        thread = get_object_or_404(Thread, pk=self.kwargs.get('pk'))
        new_post.thread = thread
        new_post.save()
        return super(PostListView, self).form_valid(form)


class LockThreadView(LoginRequiredMixin,
                     UserPassesTestMixin,
                     View):
    login_url = LOGIN_URL
    redirect_unauthenticated_users = True

    def test_func(self, user):
        return user_is_active_moderator_or_admin(user)

    def post(self, request, *args, **kwargs):
        thread_pk = self.kwargs.get('pk')
        thread = get_object_or_404(Thread, pk=thread_pk)
        thread.locked = True
        thread.save()
        return redirect('bulletin:post-list', pk=thread_pk)


class UnlockThreadView(LoginRequiredMixin,
                       UserPassesTestMixin,
                       View):
    login_url = LOGIN_URL
    redirect_unauthenticated_users = True

    def test_func(self, user):
        return user_is_active_moderator_or_admin(user)

    def post(self, request, *args, **kwargs):
        thread_pk = self.kwargs.get('pk')
        thread = get_object_or_404(Thread, pk=thread_pk)
        thread.locked = False
        thread.save()
        return redirect('bulletin:post-list', pk=thread_pk)


class StickyThreadView(LoginRequiredMixin,
                       UserPassesTestMixin,
                       View):
    login_url = LOGIN_URL
    redirect_unauthenticated_users = True

    def test_func(self, user):
        return user_is_active_moderator_or_admin(user)

    def post(self, request, *args, **kwargs):
        thread_pk = self.kwargs.get('pk')
        thread = get_object_or_404(Thread, pk=thread_pk)
        thread.sticky = True
        thread.save()
        return redirect('bulletin:post-list', pk=thread_pk)


class UnstickyThreadView(LoginRequiredMixin,
                         UserPassesTestMixin,
                         View):
    login_url = LOGIN_URL
    redirect_unauthenticated_users = True

    def test_func(self, user):
        return user_is_active_moderator_or_admin(user)

    def post(self, request, *args, **kwargs):
        thread_pk = self.kwargs.get('pk')
        thread = get_object_or_404(Thread, pk=thread_pk)
        thread.sticky = False
        thread.save()
        return redirect('bulletin:post-list', pk=thread_pk)

bulletin_board_system/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, View
from django.http import HttpResponseForbidden
from django.shortcuts import redirect

from django.contrib.auth.mixins import LoginRequiredMixin
from braces import views

from bulletin.permissions import user_is_active_moderator_or_admin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class BanUserView(View):

    def post(self, request, *args, **kwargs):
        user_to_ban = User.objects.get(username=self.kwargs.get('username'))
        if request.user == user_to_ban:
            return HttpResponseForbidden('You are not allowed to ban yourself.')
        if not (request.user.is_staff or request.user.is_superuser):
            return HttpResponseForbidden('You must be a moderator or administrator to ban others.')
        user_to_ban.banned = True
        user_to_ban.save()
        print("HELLO")
        return redirect('users:detail', username=user_to_ban.username)


class UnbanUserView(View):

    def post(self, request, *args, **kwargs):
        user_to_ban = User.objects.get(username=self.kwargs.get('username'))
        if request.user == user_to_ban:
            return HttpResponseForbidden('You are not allowed to unban yourself.')
        if not (request.user.is_staff or request.user.is_superuser):
            return HttpResponseForbidden('You must be a moderator or administrator to unban others.')
        user_to_ban.banned = False
        user_to_ban.save()
        return redirect('users:detail', username=user_to_ban.username)

bulletin_board_system/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

bulletin_board_system/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Bulletin Board System{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Bulletin Board System</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'bulletin:board-list' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}
      <div class="container-fluid" style="padding-top: 2rem;">
        {% block content %}
            <p>Use this document as a way to quick start any new project.</p>
          {% endblock content %}
      </div>


    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>